### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by brianjmurrell** [hoehermann/purple-gowhatsapp#64]
I'm getting an invalid memory access error from purple-gowhatsapp:

```
(07:54:37) gowhatsapp: 0x559e85a9a0e0 recieved message type -1 at 0 id (null) remote (null) sender (null) (fromMe 0, system 0): keepAlive failed: connection timed out
(07:54:37) connection: Connection error on 0x559e85a9a0e0 (reason: 16 description: keepAlive failed: connection timed out)
(07:54:37) account: Disconnecting account brianjmurrell@s.whatsapp.net (0x559e84006650)
(07:54:37) connection: Disconnecting connection 0x559e85a9a0e0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7f4f27471dfb]

goroutine 1185 [running]:
github.com/Rhymen/go-whatsapp.(*Conn).readPump.func2(0xc00029c0e0, 0xc0001e4000, 0xc0003200a0, 0xc000320090, 0xc000033e60)
	/purple-gowhatsapp/go/src/github.com/Rhymen/go-whatsapp/read.go:30 +0x2b
created by github.com/Rhymen/go-whatsapp.(*Conn).readPump
	/purple-gowhatsapp/go/src/github.com/Rhymen/go-whatsapp/read.go:29 +0x11e
```

The stacktrace in gdb is pretty much the same thing:

```
Thread 1 (Thread 0x7f4f24847700 (LWP 845612)):
#0  runtime.raise () at /usr/lib/golang/src/runtime/sys_linux_amd64.s:165
#1  0x00007f4f27153e1b in runtime.dieFromSignal (sig=6) at /usr/lib/golang/src/runtime/signal_unix.go:729
#2  0x00007f4f27153faa in runtime.crash () at /usr/lib/golang/src/runtime/signal_unix.go:821
#3  0x00007f4f2713e376 in runtime.fatalpanic (msgs=0xc000043700) at /usr/lib/golang/src/runtime/panic.go:1216
        docrash = true
        gp = <optimized out>
#4  0x00007f4f2713dd11 in runtime.gopanic (e=...) at /usr/lib/golang/src/runtime/panic.go:1064
        gp = 0xc000468d80
        p = {argp = 0x0, arg = {_type = 0x7f4f275b5f60, data = 0xc00027cb40}, link = 0x0, pc = 0, sp = 0x0, recovered = false, aborted = false, goexit = false}
#5  0x00007f4f27153d3e in runtime.panicmem () at /usr/lib/golang/src/runtime/signal_unix.go:702
        g = <optimized out>
#6  runtime.sigpanic () at /usr/lib/golang/src/runtime/signal_unix.go:695
        g = <optimized out>
#7  0x00007f4f27471dfb in github.com/Rhymen/go-whatsapp.(*Conn).readPump.func2 (wac=0xc00029c0e0, &msgType=0xc0001e4000, &reader=0xc0003200a0, &readErr=0xc000320090, readerFound=0xc000033e60) at /net/server/src/purple-gowhatsapp/go/src/github.com/Rhymen/go-whatsapp/read.go:30
#8  0x00007f4f2716d4e1 in runtime.goexit () at /usr/lib/golang/src/runtime/asm_amd64.s:1373
#9  0x000000c00029c0e0 in  ()
#10 0x000000c0001e4000 in  ()
#11 0x000000c0003200a0 in  ()
#12 0x000000c000320090 in  ()
#13 0x000000c000033e60 in  ()
#14 0x0000000000000000 in  ()
```

**Comment by hoehermann** [comment]
Judging by the stack-trace, this seems to happen entirely in the go-whatsapp part – not in the purple plug-in's code. I'll leave this as "not mine" for now or until proven guilty. ;) I might find time to investigate this in October.

**Comment by brianjmurrell** [comment]
Pity.  I was liking having whatsapp in pidgin now that the use-of-freed-memory issue was fixed.

**Comment by hoehermann** [comment]
I like software not crashing and having WhatsApp in Pidgin, too. :)

**Comment by hoehermann** [comment]
This is apparently happening in https://github.com/Rhymen/go-whatsapp/issues/458 and needs to be fixed there.
